# Generated by Django 5.0.3 on 2024-03-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordem",
                    models.CharField(
                        choices=[("RECEITA", "RECEITA"), ("DESPESA", "DESPESA")],
                        max_length=10,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=150, verbose_name="descrição"),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Salário", "Salário"),
                            ("Renda Extra", "Renda Extra"),
                            ("Renda Passiva", "Renda Passiva"),
                            ("Investimento", "Investimento"),
                            ("Skin", "Skin"),
                            ("Transporte", "Transporte"),
                            ("Moradia", "Moradia"),
                            ("Alimentação", "Alimentação"),
                            ("Lazer", "Lazer"),
                            ("Outros", "Outros"),
                        ],
                        max_length=25,
                    ),
                ),
                ("periodo", models.DateField()),
                ("fixo", models.BooleanField()),
                ("credito", models.BooleanField(verbose_name="crédito")),
            ],
        ),
    ]
